/**
 * Airline IATA codes (plus alliance pseudo-codes ONEWORLD / SKYTEAM / STAR_ALLIANCE).
 *
 * Auto-generated from data/airlines.csv — run `bun run generate:enums` to refresh.
 */
/** Map of IATA code → human-readable name (raw lookup, no enum wrapping). */
export const AIRLINE_NAMES: Record<string, string> = {
  A0: "Macair Jet",
  A1: "APG Distribution System",
  A2: "Astra Airlines",
  A3: "Aegean Airlines",
  A4: "Azimuth",
  A5: "HOP!",
  A6: "Yunnan Hongtu Airline",
  A7: "Aéreo Calafia",
  A8: "Aerolink Uganda",
  A9: "Georgian Airways",
  AA: "American Airlines",
  AB: "Bonza",
  AC: "Air Canada",
  AD: "Azul Brazilian Airlines",
  AE: "Mandarin Airlines",
  AF: "Air France",
  AG: "Aruba Airlines",
  AH: "Air Algerie",
  AI: "Air India",
  AJ: "Aztec Worldwide Airlines",
  AK: "AirAsia",
  AL: "Air Leisure",
  AM: "AeroMexico",
  AN: "HOP Airlinair",
  AO: "Air Juan Aviation",
  AP: "AlbaStar",
  AQ: "9 Air",
  AR: "Aerolíneas Argentinas",
  AS: "Alaska Airlines",
  AT: "Royal Air Maroc",
  AU: "Austral Líneas Aéreas",
  AV: "Avianca",
  AW: "Africa World Airlines",
  AX: "Trans States Airlines",
  AY: "Finnair",
  AZ: "Alitalia",
  B0: "La Compagnie",
  B1: "Cions Software",
  B2: "Belavia",
  B3: "Bhutan Airlines",
  B4: "Zanair",
  B5: "Fly-SAX",
  B6: "JetBlue",
  B7: "Uni Airways",
  B8: "Eritrean Airlines",
  B9: "Iran Air Tours",
  BA: "British Airways",
  BB: "Seaborne Airlines",
  BC: "Skymark Airlines",
  BD: "Cambodia Bayon Airlines",
  BE: "Flybe",
  BF: "French Bee",
  BG: "Biman Bangladesh Airline",
  BH: "Hawkair",
  BI: "Royal Brunei",
  BJ: "Nouvelair",
  BK: "Okay Airways",
  BL: "Jetstar Pacific Airlines",
  BM: "bmi regional",
  BN: "Luxwing Ltd",
  BO: "BB Airways",
  BP: "Air Botswana",
  BR: "EVA Air",
  BS: "US-Bangla Airlines",
  BT: "airBaltic",
  BU: "Compagnie Africaine d'Aviation",
  BV: "Blue Panorama Airlines",
  BW: "Caribbean Airlines",
  BX: "Air Busan",
  BY: "Thomson Airways",
  BZ: "Bluebird Airways",
  C0: "Centralwings",
  C1: "Tectimes Sudamerica",
  C2: "Ceiba Intercontinental",
  C3: "Trade Air",
  C4: "Alma De Mexico",
  C5: "CommutAir",
  C6: "Canjet Airlines",
  C7: "Cinnamon Air",
  C8: "Cronos Airlines",
  C9: "Skywise",
  CA: "Air China",
  CB: "Trans Caribbean Air ExportImport",
  CC: "CM Airlines",
  CD: "Corendon Dutch Airlines",
  CE: "Chalair Aviation",
  CF: "China Postal Airlines",
  CG: "PNG Air",
  CH: "Bemidji Airlines",
  CI: "China Airlines",
  CJ: "BA CityFlyer",
  CK: "China Cargo Airlines",
  CL: "Lufthansa CityLine",
  CM: "Copa Airlines",
  CN: "Grand China Air",
  CO: "Cobalt Air",
  CP: "Compass Airlines",
  CQ: "Coastal Travels",
  CR: "OAG Worldwide",
  CS: "Comlux Aruba",
  CT: "Alitalia CityLiner",
  CU: "Cubana De Aviacion",
  CV: "Cargolux",
  CX: "Cathay Pacific",
  CY: "Charlie Airlines",
  CZ: "China Southern Airlines",
  D0: "DHL Air UK",
  D2: "Severstal Air Company",
  D3: "Daallo Airlines",
  D4: "DART Ltd",
  D6: "Interair",
  D7: "AirAsia X",
  D8: "Norwegian Air International",
  D9: "Donavia",
  DA: "Air Georgia",
  DB: "HOP Brit Air",
  DC: "Braathens Regional Airways",
  DD: "Nok Air",
  DE: "Condor",
  DF: "Condor Berlin",
  DG: "Cebgo",
  DH: "Douniah Airlines",
  DI: "Norwegian Air UK",
  DJ: "AirAsia Japan",
  DK: "Thomas Cook Airlines",
  DL: "Delta Air Lines",
  DM: "Arajet",
  DN: "Norwegian Air Argentina",
  DO: "Discovery Airways",
  DP: "Pobeda",
  DQ: "Delta Connection",
  DR: "Ruili Airlines",
  DS: "easyJet Switzerland",
  DT: "Taag",
  DU: "Norwegian Long Haul",
  DV: "SCAT Airlines",
  DW: "Great Dane Airlines",
  DX: "Danish Air Transport",
  DY: "Norwegian Air Shuttle (NAS)",
  DZ: "Donghai Airlines",
  E2: "Eurowings Europe",
  E3: "New Gen Airways",
  E4: "Enter Air",
  E5: "Air Arabia Egypt",
  E6: "Bringer Air Cargo",
  E7: "Equaflight Service",
  E8: "City Airways",
  E9: "Evelop Airlines",
  EB: "Wamos Air",
  EC: "easyJet Europe",
  ED: "Air Explore",
  EE: "Nordica",
  EF: "Fly CamInter",
  EG: "East Air",
  EH: "ANA Wings",
  EI: "Aer Lingus",
  EJ: "New England Airlines",
  EK: "Emirates",
  EL: "Ellinair",
  EM: "Aero Benin",
  EN: "Air Dolomiti",
  EO: "Air Go Egypt",
  EP: "Iran Aseman Airlines",
  EQ: "TAME",
  ER: "SereneAir",
  ES: "DHL International Aviation ME",
  ET: "Ethiopian Airlines",
  EU: "Chengdu Airlines",
  EV: "ExpressJet Airlines",
  EW: "Eurowings",
  EX: "Avianca Express",
  EY: "Etihad Airways",
  EZ: "Sun Air of Scandinavia",
  F1: "Farelogix",
  F2: "Safarilink Aviation",
  F3: "Flyadeal",
  F4: "Air Flamenco",
  F6: "Fly2sky",
  F7: "Etihad Regional",
  F8: "Flair Airlines",
  F9: "Frontier Airlines",
  FA: "Safair",
  FB: "Bulgaria Air",
  FC: "Fly Corporate",
  FD: "Thai AirAsia",
  FE: "Far Eastern Air Transport",
  FG: "Ariana Afghan Airlines",
  FH: "Freebird Airlines",
  FI: "Icelandair",
  FJ: "Fiji Airways",
  FK: "Kelowna Flightcraft Air Charter",
  FL: "Airtran Airways",
  FM: "Shanghai Airlines",
  FN: "Royal Air Maroc Express",
  FO: "Felix Airways",
  FP: "Pelican Airlines",
  FQ: "SOL SA LINEAS AEREAS (DBA Flyest Lineas Aereas)",
  FR: "Ryanair",
  FS: "Flyr",
  FT: "FlyEgypt",
  FU: "Fuzhou Airlines",
  FV: "Rossiya",
  FW: "Ibex Airlines",
  FX: "Fedex",
  FY: "Flyfirefly",
  FZ: "flydubai",
  G0: "Alianza Glancelot",
  G2: "Galeyr Airline",
  G3: "Gol Transportes Aéreos",
  G4: "Allegiant Air",
  G5: "China Express Airlines",
  G6: "Denim Air",
  G7: "GoJet Airlines",
  G8: "Go First",
  G9: "Air Arabia",
  GA: "Garuda Indonesia",
  GB: "ABX Air",
  GC: "Global Feeder Services",
  GD: "Aviair",
  GE: "TransAsia Airways",
  GF: "Gulf Air",
  GG: "Sky Lease Cargo",
  GH: "Globus",
  GI: "Itek Air",
  GJ: "Zhejiang Loong Airlines",
  GK: "Jetstar Japan",
  GL: "Air Greenland",
  GM: "Chair Airlines",
  GO: "Go",
  GP: "APG Airlines",
  GQ: "Sky Express",
  GR: "Aurigny Air Services",
  GS: "Tianjin Airlines",
  GT: "Air Guilin",
  GU: "Aviateca",
  GV: "Grant Aviation",
  GW: "SkyGreece Airlines",
  GX: "Guangxi Beibu Gulf Airlines",
  GY: "Colorful Guizhou Airlines",
  GZ: "Air Rarotonga",
  H1: "Hahn Air Systems",
  H2: "Sky Airline",
  H3: "Harbour Air",
  H6: "Bulgarian Air Charter",
  H7: "Eagle Air",
  H8: "Chilejet",
  H9: "Himalaya Airlines",
  HA: "Hawaiian Airlines",
  HB: "Asia Atlantic Airlines",
  HC: "Air Senegal",
  HD: "Air Do",
  HE: "LGW Luftfahrtges Walter",
  HF: "Air Cote D Ivoire",
  HH: "Taban Airlines",
  HI: "Papillon Airways",
  HJ: "Hellas Jet",
  HK: "Skippers Aviation",
  HL: "",
  HM: "Air Seychelles",
  HN: "Afghan Jet International",
  HO: "Juneyao Airlines",
  HP: "Amapola Flyg",
  HQ: "Thomas Cook Airlines Belgium",
  HR: "Hahn Air",
  HS: "Heli Sécurité",
  HU: "Hainan Airlines",
  HV: "Transavia Airlines",
  HW: "North Wright Air",
  HX: "Hong Kong Airlines",
  HY: "Uzbekistan Airways",
  HZ: "Aurora Airlines",
  I1: "CTS Viaggi",
  I2: "Iberia Express",
  I3: "ATA Airlines",
  I4: "Scott Air",
  I5: "AirAsia India",
  I6: "Air Indus",
  I7: "Int'Air Îles",
  I8: "Izhavia",
  IA: "Iraqi Airways",
  IB: "Iberia",
  IC: "Nacil Indian Airline",
  ID: "Batik Air",
  IE: "Solomon Airlines",
  IF: "FlyBaghdad",
  IG: "Air Italy",
  IH: "Jsc Irtysh Air",
  II: "IBC Airways",
  IJ: "Spring Airlines Japan",
  IK: "Air Kiribati",
  IL: "Trigana Air Service",
  IM: "Mint Líneas Aéreas",
  IN: "NAM Air",
  IO: "IrAero",
  IP: "Iberworld Airlines",
  IQ: "Qazaq Air",
  IR: "Iran Air",
  IS: "AIS Airlines",
  IT: "Tigerair Taiwan",
  IU: "Hevilift",
  IV: "Air Djibouti",
  IW: "Wings Air",
  IX: "Air India Express",
  IY: "Yemen Airways",
  IZ: "Arkia",
  J0: "Jetlink Express",
  J1: "OntJet",
  J2: "Azerbaijan Airlines",
  J3: "Northwestern Air Lease",
  J4: "Badr Airlines",
  J5: "Alaska Seaplane Service",
  J6: "Jet-Ops",
  J7: "Afrijet Business Service",
  J8: "Berjaya Air",
  J9: "Jazeera Airways",
  JA: "Jetsmart",
  JB: "Helijet International",
  JC: "Japan Air Commuter",
  JD: "Beijing Capital Airlines",
  JE: "Mango",
  JF: "Jet Asia Airways",
  JG: "Jetgo Australia",
  JH: "Fuji Dream Airlines",
  JI: "Eastern Caribbean Airlines",
  JJ: "LATAM Brasil",
  JL: "Japan Airlines",
  JM: "Jambojet",
  JN: "Alaska Air Transit",
  JO: "Jet Time",
  JQ: "Jetstar",
  JR: "Joy Air",
  JS: "Air Koryo",
  JT: "Lion Air",
  JU: "Air Serbia",
  JV: "Bearskin Airlines",
  JW: "Vanilla Air",
  JX: "DAC East Africa",
  JY: "InterCaribbean Airways",
  K3: "Taquan Air Services",
  K4: "ALS",
  K5: "SeaPort",
  K6: "Cambodia Angkor Air",
  K7: "Air KBZ",
  K8: "Kan Air",
  K9: "Kalitta Charters",
  KA: "Cathay Dragon",
  KB: "Druk Air",
  KC: "Air Astana",
  KD: "Western Global Airlines",
  KE: "Korean Air",
  KF: "Air Belgium",
  KG: "Aerogaviota",
  KH: "Aloha Air Cargo",
  KI: "KrasAvia",
  KJ: "Air Incheon",
  KK: "AtlasGlobal",
  KL: "KLM",
  KM: "Air Malta",
  KN: "China United Airlines",
  KO: "Komiaviatrans",
  KP: "ASKY Airlines",
  KQ: "Kenya Airways",
  KR: "Air Bishkek",
  KS: "Penair",
  KT: "Fly Kiss",
  KU: "Kuwait Airways",
  KV: "Sky Regional Airlines",
  KW: "Kharkiv Airlines",
  KX: "Cayman Airways",
  KY: "Kunming Airlines",
  KZ: "Nippon Cargo Airlines",
  L1: "E Savtravel",
  L3: "Lynx Aviation",
  L4: "Air Service Liege (ASL)",
  L5: "Atlantique Air Assistance",
  L6: "Mauritanian Airlines Int",
  L7: "Lugansk Airlines",
  L8: "Afric Aviation",
  L9: "Belle Air Europe",
  LA: "LATAM Chile",
  LB: "Air Costa",
  LC: "ECAir",
  LE: "Norwegian Air Sweden AB",
  LF: "Contour Airlines",
  LG: "Luxair",
  LH: "Lufthansa Cargo",
  LI: "LIAT",
  LJ: "Jin Air",
  LK: "Lao Skyway",
  LL: "Miami Air International",
  LM: "Loganair",
  LN: "Libyan Airlines",
  LO: "LOT Polish Airlines",
  LP: "LATAM Perú",
  LQ: "Lanmei Airlines",
  LR: "Avianca Costa Rica",
  LS: "Jet2.com",
  LT: "Longjiang Airlines",
  LU: "LAN Express",
  LV: "Level",
  LW: "Pacific Wings",
  LX: "Swiss International Air Lines",
  LY: "El Al",
  LZ: "Swiss Global Air Lines",
  M0: "Aero Mongolia",
  M2: "MHS Aviation",
  M3: "Air Norway",
  M4: "Mistral Air",
  M5: "Kenmore Air",
  M6: "Amerijet International",
  M8: "SKYJET Airlines",
  M9: "Motor Sich Jsc",
  MB: "Mng Airlines Cargo",
  MC: "Air Mobility Command",
  MD: "Air Madagascar",
  ME: "Middle East Airlines",
  MF: "XiamenAir",
  MG: "Miami Air Lease",
  MH: "Malaysia Airlines",
  MI: "SilkAir",
  MJ: "Mihin Lanka",
  MK: "Air Mauritius",
  ML: "Sky Mali",
  MM: "Peach Aviation",
  MN: "Comair",
  MO: "Calm Air International",
  MP: "Martinair",
  MQ: "Envoy Air",
  MR: "Hunnu Air",
  MS: "EgyptAir",
  MT: "Thomas Cook Airlines",
  MU: "China Eastern Airlines",
  MV: "Air Mediterranean",
  MW: "Mokulele Airlines",
  MX: "Breeze Airways",
  MY: "MASwings",
  MZ: "Amakusa Airlines",
  N0: "Norse Atlantic Airways",
  N2: "Dagestan Airlines",
  N3: "Aerolineas Mas",
  N4: "Nord Wind",
  N5: "Nolinor Aviation",
  N6: "Nomad Aviation",
  N7: "Nordic Regional Airlines",
  N8: "National Airlines",
  N9: "Novair",
  NB: "Skypower Express Airways",
  NC: "Cobham Aviation Services Australia",
  ND: "FMI Air",
  NE: "Nesma Airlines",
  NF: "Air Vanuatu",
  NG: "NovAir",
  NH: "All Nippon Airways",
  NI: "Portugalia",
  NJ: "Niger Airways",
  NK: "Spirit Airlines",
  NL: "Aero4M",
  NM: "Manx",
  NN: "Vim Airlines",
  NO: "Neos",
  NP: "Nile Air",
  NQ: "Air Japan",
  NR: "Manta Air",
  NS: "Hebei Airlines",
  NT: "Binter Canarias",
  NU: "Japan Transocean Air",
  NV: "Iranian Naft Airline",
  NW: "Northwest Airlines",
  NX: "Air Macau",
  NY: "Air Iceland",
  NZ: "Air New Zealand",
  O2: "Jet Air",
  O4: "Antrak Air",
  O5: "Comores Aviation International",
  O7: "Orenburg Region Airlines",
  O9: "Nova Airways",
  OA: "Olympic Air",
  OB: "Boliviana de Aviación (BoA)",
  OC: "Oriental Air Bridge",
  OD: "Malindo Airways",
  OE: "Lauda",
  OF: "Overland Airways",
  OG: "Air Freight NZ",
  OH: "PSA Airlines",
  OI: "Hinterland Aviation",
  OJ: "Fly Jamaica Airways",
  OK: "Czech Airlines",
  OL: "Polynesian Airlines",
  OM: "Miat Mongolian Airlines",
  ON: "Nauru Airlines",
  OO: "SkyWest Airlines",
  OP: "Air Pegasus",
  OQ: "Chongqing Airlines",
  OR: "TUI Airlines Netherlands",
  OS: "Austrian Airlines",
  OT: "Tchadia Airlines",
  OU: "Croatia Airlines",
  OV: "SalamAir",
  OW: "Skyward Express",
  OX: "Orient Thai Airlines",
  OY: "Andes Líneas Aéreas",
  OZ: "Asiana Airlines",
  P0: "Proflight Commuter",
  P1: "Publiccharters Com",
  P2: "Airkenya Express",
  P3: "CargoLogicAir",
  P4: "Aerolineas Sosa",
  P5: "Copa Airlines Colombia",
  P6: "Pascan Aviation",
  P8: "SprintAir",
  P9: "Peruvian Airlines",
  PA: "Airblue",
  PB: "Provincial Airlines",
  PC: "Pegasus Airlines",
  PD: "Porter Airlines",
  PE: "Peoples Viennaline",
  PF: "Primera Air Scandinavia",
  PG: "Bangkok Airways",
  PH: "Transavia Denmark",
  PI: "Polar Airlines",
  PJ: "Air Saint Pierre",
  PK: "Pakistan International Airlines (PIA)",
  PL: "Southern Air Charter",
  PM: "Canaryfly",
  PN: "China West Air",
  PO: "Polar Air Cargo",
  PP: "Jet Aviation Business",
  PQ: "AirAsia Philippines",
  PR: "Philippine Airlines",
  PS: "Ukraine International Airlines",
  PT: "Piedmont Airlines",
  PU: "Plus Ultra Líneas Aéreas",
  PV: "Saint Barth Commuter",
  PW: "Precision Air",
  PX: "Air Niugini",
  PY: "Surinam Airways",
  PZ: "LATAM Paraguay",
  Q0: "Quebecair Express",
  Q1: "Sqiva Sistem",
  Q2: "Maldivian",
  Q3: "Anguilla Air Services",
  Q4: "Aviation Starlink",
  Q5: "Forty Mile Air",
  Q7: "Sky Bahamas Airlines",
  Q8: "Trans Air Congo",
  Q9: "Airliaison",
  QA: "Cimber",
  QB: "Qeshm Air",
  QC: "Camair-Co",
  QD: "Dobrolet Airlines",
  QE: "Fars Qeshm Airlines",
  QF: "Qantas",
  QG: "Citilink Indonesia",
  QH: "Air Bamboo",
  QJ: "Latpass Airlines",
  QK: "Jazz Aviation",
  QL: "Linea Aerea De Servicio",
  QM: "Monacair",
  QN: "Skytrans Regional",
  QO: "Quantum Air",
  QP: "Air Kenya Aviation",
  QQ: "Alliance Airlines",
  QR: "Qatar Airways",
  QS: "Smartwings",
  QT: "Tampa Cargo",
  QU: "UTair Ukraine",
  QV: "Lao Airlines",
  QW: "Qingdao Airlines",
  QX: "Horizon Air",
  QY: "European Air Transport",
  QZ: "Indonesia AirAsia",
  R0: "MS Royal Airlines",
  R2: "Transair",
  R3: "Yakutia Airlines",
  R4: "Real Tonga",
  R5: "Jordan Aviation",
  R6: "DOT LT",
  R7: "Aserca",
  R8: "Kyrgyzstan Airlines",
  R9: "TAF Linhas Aereas",
  RA: "Nepal Airlines",
  RB: "Syrian Arab Airlines",
  RC: "Atlantic Airways",
  RE: "Stobart Air",
  RF: "Aero K",
  RG: "Rotana Jet",
  RH: "Robin Hood Aviation",
  RI: "Air Costa Rica",
  RJ: "Royal Jordanian",
  RK: "Region Airline",
  RL: "Royal Flight",
  RM: "Aircompany Armenia",
  RN: "Rayani Air",
  RO: "TAROM",
  RP: "Chautauqua Airlines",
  RQ: "Kam Air",
  RR: "Royal Air Force",
  RS: "Air Seoul",
  RT: "Rainbow Airlines",
  RU: "Air Bridge Cargo",
  RV: "Air Canada Rouge",
  RW: "Royal Air Charter Service",
  RX: "Regent Airways",
  RY: "Jiangxi Air",
  RZ: "SANSA Airlines",
  S0: "Aerolineas Sosa",
  S1: "Lufthansa Systems",
  S2: "Jet Lite",
  S3: "SBA Airlines",
  S4: "SATA International",
  S5: "Shuttle America",
  S6: "Sunrise Airways",
  S7: "S7 Airlines",
  S8: "Sounds Air",
  S9: "Starbow",
  SA: "South African Airways",
  SB: "Aircalin",
  SC: "Shandong Airlines",
  SD: "Sudan Airways",
  SF: "Tassili Airlines",
  SG: "SpiceJet",
  SH: "Sharp Aviation",
  SI: "Blue Islands",
  SJ: "Sriwijaya Air",
  SK: "Scandinavian Airlines",
  SL: "Thai Lion Air",
  SM: "Air Cairo",
  SN: "Brussels Airlines",
  SO: "Apex Airline",
  SP: "SATA Air Açores",
  SQ: "Singapore Airlines",
  SR: "SundAir",
  SS: "Corsair",
  ST: "Germania",
  SU: "Aeroflot",
  SV: "Saudia",
  SW: "Air Namibia",
  SX: "SkyWork Airlines",
  SY: "Sun Country",
  SZ: "Somon Air",
  T0: "Avianca Perú",
  T1: "Tik Systems",
  T2: "Fly Art",
  T3: "Eastern Airways",
  T4: "Trip",
  T5: "Turkmenistan Airlines",
  T6: "ITI Air",
  T7: "Twin Jet",
  T9: "Aviator Aviation",
  TA: "Avianca El Salvador",
  TB: "TUIfly Belgium",
  TC: "Air Tanzania",
  TD: "Atlantis European Airways",
  TE: "Sky Taxi",
  TF: "Braathens Regional Aviation",
  TG: "Thai Airways",
  TH: "Raya Airways",
  TI: "Tailwind Hava Yollari As",
  TJ: "Tradewind Aviation",
  TK: "Turkish Airlines",
  TL: "Airnorth",
  TM: "Lam Mozambique",
  TN: "Air Tahiti Nui",
  TO: "Transavia France",
  TP: "TAP Portugal",
  TQ: "Tandem Aero",
  TR: "Scoot",
  TS: "Air Transat",
  TT: "Tigerair Australia",
  TU: "Tunisair",
  TV: "Tibet Airlines",
  TW: "T'way Air",
  TX: "Air Caraibes",
  TY: "Air Caledonie",
  U1: "Videcom International",
  U2: "easyJet",
  U3: "Avies",
  U4: "Buddha Air",
  U5: "Karinou Airlines",
  U6: "Ural Airlines",
  U7: "Air Uganda",
  U8: "Tus Airways",
  U9: "Tatarstan Air",
  UA: "United Airlines",
  UB: "Myanmar National Airlines",
  UC: "LAN Cargo",
  UD: "Hex Air",
  UE: "Nasair",
  UF: "Um Air",
  UG: "Tunisair Express",
  UH: "AtlasJet Ukraine",
  UI: "Auric Air Services",
  UJ: "AlMasria Universal Airlines",
  UK: "Vistara",
  UL: "SriLankan Airlines",
  UM: "Air Zimbabwe",
  UN: "Transaero Airlines",
  UO: "Hong Kong Express Airways",
  UP: "Bahamasair",
  UQ: "Business Aviation Centre",
  UR: "Uganda Airlines",
  US: "US Airways",
  UT: "UTair Aviation",
  UU: "Air Austral",
  UV: "Helicopteros Del Sureste",
  UX: "Air Europa",
  UY: "Sky Prime Charter",
  UZ: "Buraq Air",
  V0: "Conviasa",
  V1: "IBS Software Services Americas",
  V2: "Vision Airlines",
  V3: "Carpatair",
  V4: "Vieques Air Link",
  V5: "Aerovias DAP",
  V6: "Air Link",
  V7: "Volotea",
  V8: "Iliamna Air",
  V9: "Van Air Europe",
  VA: "Virgin Australia",
  VB: "Aeroenlaces Nacionales",
  VC: "ViaAir",
  VD: "Hennan Airlines",
  VE: "EasyFly",
  VF: "Fly Armenia Airways",
  VG: "VLM Airlines",
  VH: "Viva Air Colombia",
  VI: "Volga Dnepr Airline",
  VJ: "VietJet Air",
  VK: "Anisec Luftfahrt",
  VL: "Air VIA",
  VM: "Max Air",
  VN: "Vietnam Airlines",
  VO: "VLM Airlines Slovenia",
  VP: "Villa Air",
  VQ: "Novoair",
  VR: "Tacv Cabo Verde Airlines",
  VS: "Virgin Atlantic",
  VT: "Air Tahiti",
  VU: "Vuelos Economicos",
  VV: "Viva Airlines Peru",
  VW: "Aeromar",
  VX: "Virgin America",
  VY: "Vueling",
  VZ: "Thai Vietjet Air",
  W1: "WorldTicket",
  W2: "Flexflight",
  W3: "Arik Air",
  W4: "LC Péru",
  W5: "Mahan Airlines",
  W6: "Wizz Air",
  W7: "Sayakhat Airlines",
  W8: "Caribbean Winds Airlines",
  W9: "Wizz Air",
  WA: "KLM Cityhopper",
  WB: "Rwandair",
  WC: "Islena Airlines",
  WD: "Amsterdam Airlines Bv",
  WE: "Thai Smile Airways",
  WF: "Widerøe",
  WG: "Sunwing Airlines",
  WH: "West African Airlines",
  WI: "White Airways",
  WJ: "Air Labrador",
  WK: "Edelweiss Air",
  WL: "European Coastal Airlines",
  WM: "Windward Island Airways",
  WN: "Southwest Airlines",
  WO: "World Airways",
  WP: "Island Air",
  WQ: "Romavia",
  WR: "WestJet Encore",
  WS: "WestJet",
  WT: "Swiftair",
  WU: "Tikal Jets Airlines",
  WV: "Aero VIP",
  WW: "Wow Air",
  WX: "CityJet",
  WY: "Oman Air",
  WZ: "Red Wings Airlines",
  X1: "Hahn Air Technologies",
  X3: "TUIfly",
  X4: "Air Excursions",
  X6: "Airlines Reporting Corp",
  X7: "Challenge Aero",
  X9: "Avion Express",
  XB: "IATA",
  XC: "Corendon Airlines",
  XD: "Scheduled Airlines Traffic Offices",
  XE: "Delux Public Charter",
  XF: "Vladivostok Air",
  XG: "Sun Express Germany",
  XH: "Non Iata Codeshare Carrier",
  XJ: "Thai AirAsia X",
  XK: "Air Corsica",
  XL: "LATAM Ecuador",
  XM: "Zimex Aviation",
  XN: "XpressAir",
  XO: "Seair",
  XP: "Xtra Airways",
  XQ: "SunExpress",
  XR: "Corendon Airlines Europe",
  XS: "SITA",
  XT: "Indonesia AirAsia X",
  XU: "African Express Airways",
  XW: "NokScoot",
  XY: "Flynas",
  XZ: "South African Express",
  Y0: "Yellow Airtaxi",
  Y1: "Travel Technology Interactive",
  Y2: "Air Century, S.A.",
  Y3: "Gryphon Airlines",
  Y4: "Volaris",
  Y5: "Golden Myanmar Airlines",
  Y6: "AB Aviation",
  Y7: "NordStar",
  Y8: "Yangtze River Express",
  Y9: "Kish Airlines",
  YA: "Nego Airline One",
  YB: "Harbour Air Seaplanes",
  YC: "Yamal Airlines",
  YD: "Mauritania Airways",
  YE: "Yan Air",
  YG: "South Airlines",
  YH: "Yangon Airways",
  YI: "Yunnan Yingan Airline",
  YJ: "Asian Wings Airways",
  YK: "Avia Traffic Company",
  YL: "Libyan Wings",
  YM: "Montenegro Airlines",
  YN: "Air Creebec",
  YO: "Heli Air Monaco",
  YP: "Perimeter Aviation",
  YQ: "TAR Aerolíneas",
  YR: "Scenic Airlines",
  YS: "Regional",
  YT: "Yeti Airlines",
  YU: "Euroatlantic Airways",
  YV: "Mesa Airlines",
  YW: "Air Nostrum",
  YX: "Republic Airline",
  YZ: "Alas Uruguay",
  Z0: "Norse Atlantic Airways",
  Z2: "AirAsia Zest",
  Z3: "PM Air",
  Z4: "Zagrosjet",
  Z5: "GMG Airlines",
  Z6: "Dniproavia",
  Z7: "Amaszonas Uruguay",
  Z8: "Línea Aérea Amaszonas",
  Z9: "Jsc Bek Air",
  ZA: "Sky Angkor Airlines",
  ZB: "Monarch Airlines",
  ZC: "Fly Africa Zimbabwe",
  ZD: "Ewa Air",
  ZE: "Eastar Jet",
  ZF: "Azur Air",
  ZG: "Zipair",
  ZH: "Shenzhen Airlines",
  ZI: "Aigle Azur",
  ZJ: "Zambezi Airlines",
  ZK: "Great Lakes Airlines",
  ZL: "Regional Express",
  ZM: "Pegasus Asia",
  ZN: "Naysa",
  ZP: "Paranair",
  ZQ: "Azman Air",
  ZR: "Punto Azul",
  ZS: "Kazaviaspas",
  ZT: "Titan Airways",
  ZU: "Sunair",
  ZV: "V Air",
  ZW: "Air Wisconsin",
  ZX: "Air Georgian",
  ZY: "China Air Cargo",
  ZZ: "Airline Service",
  _0B: "Blue Air",
  _0C: "Catovair",
  _0J: "Premium Jet AG",
  _0O: "STA Travel",
  _0P: "Palau Pacific Airways",
  _0V: "Vietnam Air Services Company",
  _0W: "W Caribbean Costa Rica",
  _1A: "Amadeus",
  _1B: "Abacus",
  _1C: "EDS Information Business",
  _1D: "Raddix Solutions",
  _1E: "Travelsky Technology",
  _1F: "Infini Travel Information",
  _1G: "Travelport Galileo",
  _1H: "Sirena Travel",
  _1I: "Netjets Aviation",
  _1J: "Axess International",
  _1K: "Sutra",
  _1L: "Navitaire Open Skies",
  _1M: "Sirena Jsc",
  _1N: "Navitaire New Skies",
  _1O: "Phoenix Systems Dertours",
  _1P: "Travelport Worldspan",
  _1Q: "Joint Stock Company Ital",
  _1R: "Bird Information Systems",
  _1S: "Sabre",
  _1T: "East Line",
  _1U: "ITA Software",
  _1V: "Galileo International",
  _1W: "Sabre",
  _1X: "Branson Air Express",
  _1Y: "Electronic Data Systems (EDS)",
  _1Z: "Fantasia Info Network",
  _2A: "Deutsche Bahn",
  _2B: "Albawings",
  _2C: "SNCF",
  _2D: "Eastern Airlines, LLC",
  _2E: "Smokey Bay Air",
  _2F: "Fair Aviation",
  _2G: "Angara Airlines",
  _2H: "Thalys",
  _2I: "Star Perú",
  _2J: "Air Burkina",
  _2K: "Aerolineas Galapagos",
  _2L: "Helvetic Airways",
  _2M: "Maya Island Air",
  _2N: "Nextjet",
  _2O: "Redemption",
  _2P: "PAL Express",
  _2Q: "Air Cargo Carriers",
  _2R: "VIA Rail Canada",
  _2S: "Air Carnival",
  _2T: "Timbis Air",
  _2U: "Ero Sun d'Or",
  _2V: "Amtrak",
  _2W: "World 2 Fly, S.L",
  _2Z: "Passaredo Transportes",
  _3A: "Chu Kong Passenger Transport",
  _3B: "Job Air",
  _3C: "Air Chathams",
  _3D: "Dokasch",
  _3E: "Multi Aero",
  _3F: "FlyOne Armenia",
  _3G: "AsiaCargo Express",
  _3H: "Air Inuit",
  _3I: "Pison Airways Ltd",
  _3J: "Jubba Airways Kenya",
  _3K: "Jetstar Asia Airways",
  _3L: "Air Arabia Abu Dhabi",
  _3M: "Silver Airways",
  _3N: "Air Urga",
  _3O: "Air Arabia Maroc",
  _3P: "World 2 Fly Portugal",
  _3Q: "Carib Aviation Limited",
  _3R: "Divi Divi Air",
  _3S: "Air Antilles Express",
  _3T: "Tarco Air",
  _3U: "Sichuan Airlines",
  _3V: "Tnt Airways",
  _3W: "Malawian Airlines",
  _3X: "Premier Trans Aire",
  _3Z: "Travel Service Polska",
  _4A: "Aero Transporte",
  _4B: "Aviastar TU",
  _4C: "LATAM Colombia",
  _4D: "Air Sinai",
  _4E: "Tanana Air Service",
  _4F: "Freedom Airline Express",
  _4G: "Gazpromavia",
  _4H: "United Airways Bangladesh",
  _4I: "Ihy Izmir Havayollari",
  _4J: "Flydamas Airlines",
  _4K: "Air Askari Aviation",
  _4L: "Palau National Airlines",
  _4M: "LATAM Argentina",
  _4N: "Air North",
  _4O: "Interjet",
  _4P: "Travel Air",
  _4Q: "Safi Airways",
  _4R: "Star East Airline",
  _4S: "Star Airways",
  _4T: "Belair Airlines",
  _4U: "Germanwings",
  _4V: "Lacbravo",
  _4W: "Warbelows Air Ventures",
  _4X: "Atlantic Express Airline",
  _4Y: "Discover Airlines",
  _4Z: "Airlink",
  _5B: "Bassaka Air",
  _5C: "Challenge Aero",
  _5D: "Aeroméxico Connect",
  _5E: "Aero",
  _5F: "Fly One",
  _5H: "Five Fourty Aviation",
  _5I: "ALSA",
  _5J: "Cebu Pacific",
  _5K: "Hi Fly",
  _5L: "Fly Salone",
  _5M: "Montserrat Airways",
  _5N: "Jsc Nordavia",
  _5O: "ASL Airlines France",
  _5P: "PAL Airlines",
  _5R: "RUTACA Airlines",
  _5S: "Servicios Aereos Profesionales",
  _5T: "Canadian North",
  _5U: "Transportes Aéreos Guatemaltecos",
  _5V: "Everts",
  _5W: "WESTBahn",
  _5X: "UPS Airlines",
  _5Y: "Atlas Air",
  _5Z: "CemAir",
  _6A: "Armenia Airways",
  _6B: "Tuifly Nordic",
  _6C: "Air Timor",
  _6D: "Travel Service Slovensko",
  _6E: "IndiGo",
  _6F: "Primera Air Nordic",
  _6G: "Executive Express Aviation",
  _6H: "Israir Airlines",
  _6I: "Air Alsie",
  _6J: "Solaseed Air",
  _6K: "Songbird Airways",
  _6L: "Aklak Air",
  _6M: "Air Minas Linhas Aereas",
  _6N: "Niger Airlines",
  _6O: "Orbest",
  _6Q: "Cham Wings Airlines",
  _6R: "ALROSA",
  _6S: "Saudi Gulf Airlines",
  _6T: "Air Mandalay",
  _6V: "Avanza",
  _6W: "Saratov Airlines",
  _6Y: "SmartLynx Airlines",
  _6Z: "Eurasia Air",
  _7A: "Express Air Cargo",
  _7B: "Fly Blue Crane",
  _7C: "Jeju Air",
  _7D: "MGC Aviation",
  _7E: "Sylt Air",
  _7F: "First Air",
  _7G: "StarFlyer",
  _7H: "Ravn Alaska",
  _7I: "Insel Air International",
  _7J: "Tajik Air",
  _7K: "Kogalymavia Airlines",
  _7L: "Aero Caribbean",
  _7M: "Mayair",
  _7N: "PAWA Dominicana",
  _7O: "Travel Service Hungary",
  _7P: "Air Panama",
  _7Q: "Elite Airways",
  _7R: "RusLine",
  _7S: "Ryan Air Services",
  _7T: "Trenitalia",
  _7U: "Alpha Air Transport",
  _7V: "Federal Airlines",
  _7W: "Wind Rose Aviation",
  _7Y: "Mann Yadanarpon Airlines",
  _7Z: "Halcyon Air Cabo Verde",
  _8A: "Panama Airways",
  _8B: "TransNusa Air Services",
  _8C: "Air Transport International",
  _8D: "FitsAir",
  _8E: "Bering Air",
  _8F: "STP Airways",
  _8G: "Mid Africa Aviation",
  _8H: "BH Air",
  _8I: "Insel Air Aruba",
  _8J: "Línea Aerea Eco Jet",
  _8L: "Lucky Air",
  _8M: "Myanmar Airways International",
  _8N: "Regional Air Services",
  _8P: "Pacific Coastal Airlines",
  _8Q: "Onur Air",
  _8R: "Sol Líneas Aéreas",
  _8S: "Shun Tak China",
  _8T: "Air Tindi",
  _8U: "Afriqiyah Airways",
  _8V: "Astral Aviation",
  _8W: "Fly All Ways Airlines",
  _8Y: "Pan Pacific Airlines",
  _8Z: "Congo Airways",
  _9A: "Aladia Airlines",
  _9B: "AccesRail",
  _9C: "Spring Airlines",
  _9D: "Genghis Khan Airlines",
  _9E: "Endeavor Air",
  _9F: "Eurostar",
  _9G: "9G Rail",
  _9H: "Chang An Airlines",
  _9I: "Air India Regional",
  _9J: "Dana Air",
  _9K: "Cape Air",
  _9L: "West Link Airways",
  _9M: "Central Mountain Air",
  _9N: "Tropic Air",
  _9P: "Air Arabia Jordan",
  _9Q: "Caicos Express Airways",
  _9R: "SATENA",
  _9S: "Southern Air",
  _9T: "MyCargo Airlines",
  _9U: "Air Moldova",
  _9V: "Avior Airlines",
  _9W: "Jet Airways",
  _9X: "Southern Airways Express",
  _9Y: "National Airways",
  ONEWORLD: "Oneworld",
  SKYTEAM: "SkyTeam",
  STAR_ALLIANCE: "Star Alliance",
};

/**
 * IATA code constants. Each value equals its key so Airline.JFK === "JFK".
 * Codes that start with a digit are prefixed with "_" (e.g. Airline._3F)
 * to remain valid identifiers; the leading "_" is stripped during wire serialisation.
 */
export const Airline = {
  A0: "A0",
  A1: "A1",
  A2: "A2",
  A3: "A3",
  A4: "A4",
  A5: "A5",
  A6: "A6",
  A7: "A7",
  A8: "A8",
  A9: "A9",
  AA: "AA",
  AB: "AB",
  AC: "AC",
  AD: "AD",
  AE: "AE",
  AF: "AF",
  AG: "AG",
  AH: "AH",
  AI: "AI",
  AJ: "AJ",
  AK: "AK",
  AL: "AL",
  AM: "AM",
  AN: "AN",
  AO: "AO",
  AP: "AP",
  AQ: "AQ",
  AR: "AR",
  AS: "AS",
  AT: "AT",
  AU: "AU",
  AV: "AV",
  AW: "AW",
  AX: "AX",
  AY: "AY",
  AZ: "AZ",
  B0: "B0",
  B1: "B1",
  B2: "B2",
  B3: "B3",
  B4: "B4",
  B5: "B5",
  B6: "B6",
  B7: "B7",
  B8: "B8",
  B9: "B9",
  BA: "BA",
  BB: "BB",
  BC: "BC",
  BD: "BD",
  BE: "BE",
  BF: "BF",
  BG: "BG",
  BH: "BH",
  BI: "BI",
  BJ: "BJ",
  BK: "BK",
  BL: "BL",
  BM: "BM",
  BN: "BN",
  BO: "BO",
  BP: "BP",
  BR: "BR",
  BS: "BS",
  BT: "BT",
  BU: "BU",
  BV: "BV",
  BW: "BW",
  BX: "BX",
  BY: "BY",
  BZ: "BZ",
  C0: "C0",
  C1: "C1",
  C2: "C2",
  C3: "C3",
  C4: "C4",
  C5: "C5",
  C6: "C6",
  C7: "C7",
  C8: "C8",
  C9: "C9",
  CA: "CA",
  CB: "CB",
  CC: "CC",
  CD: "CD",
  CE: "CE",
  CF: "CF",
  CG: "CG",
  CH: "CH",
  CI: "CI",
  CJ: "CJ",
  CK: "CK",
  CL: "CL",
  CM: "CM",
  CN: "CN",
  CO: "CO",
  CP: "CP",
  CQ: "CQ",
  CR: "CR",
  CS: "CS",
  CT: "CT",
  CU: "CU",
  CV: "CV",
  CX: "CX",
  CY: "CY",
  CZ: "CZ",
  D0: "D0",
  D2: "D2",
  D3: "D3",
  D4: "D4",
  D6: "D6",
  D7: "D7",
  D8: "D8",
  D9: "D9",
  DA: "DA",
  DB: "DB",
  DC: "DC",
  DD: "DD",
  DE: "DE",
  DF: "DF",
  DG: "DG",
  DH: "DH",
  DI: "DI",
  DJ: "DJ",
  DK: "DK",
  DL: "DL",
  DM: "DM",
  DN: "DN",
  DO: "DO",
  DP: "DP",
  DQ: "DQ",
  DR: "DR",
  DS: "DS",
  DT: "DT",
  DU: "DU",
  DV: "DV",
  DW: "DW",
  DX: "DX",
  DY: "DY",
  DZ: "DZ",
  E2: "E2",
  E3: "E3",
  E4: "E4",
  E5: "E5",
  E6: "E6",
  E7: "E7",
  E8: "E8",
  E9: "E9",
  EB: "EB",
  EC: "EC",
  ED: "ED",
  EE: "EE",
  EF: "EF",
  EG: "EG",
  EH: "EH",
  EI: "EI",
  EJ: "EJ",
  EK: "EK",
  EL: "EL",
  EM: "EM",
  EN: "EN",
  EO: "EO",
  EP: "EP",
  EQ: "EQ",
  ER: "ER",
  ES: "ES",
  ET: "ET",
  EU: "EU",
  EV: "EV",
  EW: "EW",
  EX: "EX",
  EY: "EY",
  EZ: "EZ",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  FA: "FA",
  FB: "FB",
  FC: "FC",
  FD: "FD",
  FE: "FE",
  FG: "FG",
  FH: "FH",
  FI: "FI",
  FJ: "FJ",
  FK: "FK",
  FL: "FL",
  FM: "FM",
  FN: "FN",
  FO: "FO",
  FP: "FP",
  FQ: "FQ",
  FR: "FR",
  FS: "FS",
  FT: "FT",
  FU: "FU",
  FV: "FV",
  FW: "FW",
  FX: "FX",
  FY: "FY",
  FZ: "FZ",
  G0: "G0",
  G2: "G2",
  G3: "G3",
  G4: "G4",
  G5: "G5",
  G6: "G6",
  G7: "G7",
  G8: "G8",
  G9: "G9",
  GA: "GA",
  GB: "GB",
  GC: "GC",
  GD: "GD",
  GE: "GE",
  GF: "GF",
  GG: "GG",
  GH: "GH",
  GI: "GI",
  GJ: "GJ",
  GK: "GK",
  GL: "GL",
  GM: "GM",
  GO: "GO",
  GP: "GP",
  GQ: "GQ",
  GR: "GR",
  GS: "GS",
  GT: "GT",
  GU: "GU",
  GV: "GV",
  GW: "GW",
  GX: "GX",
  GY: "GY",
  GZ: "GZ",
  H1: "H1",
  H2: "H2",
  H3: "H3",
  H6: "H6",
  H7: "H7",
  H8: "H8",
  H9: "H9",
  HA: "HA",
  HB: "HB",
  HC: "HC",
  HD: "HD",
  HE: "HE",
  HF: "HF",
  HH: "HH",
  HI: "HI",
  HJ: "HJ",
  HK: "HK",
  HL: "HL",
  HM: "HM",
  HN: "HN",
  HO: "HO",
  HP: "HP",
  HQ: "HQ",
  HR: "HR",
  HS: "HS",
  HU: "HU",
  HV: "HV",
  HW: "HW",
  HX: "HX",
  HY: "HY",
  HZ: "HZ",
  I1: "I1",
  I2: "I2",
  I3: "I3",
  I4: "I4",
  I5: "I5",
  I6: "I6",
  I7: "I7",
  I8: "I8",
  IA: "IA",
  IB: "IB",
  IC: "IC",
  ID: "ID",
  IE: "IE",
  IF: "IF",
  IG: "IG",
  IH: "IH",
  II: "II",
  IJ: "IJ",
  IK: "IK",
  IL: "IL",
  IM: "IM",
  IN: "IN",
  IO: "IO",
  IP: "IP",
  IQ: "IQ",
  IR: "IR",
  IS: "IS",
  IT: "IT",
  IU: "IU",
  IV: "IV",
  IW: "IW",
  IX: "IX",
  IY: "IY",
  IZ: "IZ",
  J0: "J0",
  J1: "J1",
  J2: "J2",
  J3: "J3",
  J4: "J4",
  J5: "J5",
  J6: "J6",
  J7: "J7",
  J8: "J8",
  J9: "J9",
  JA: "JA",
  JB: "JB",
  JC: "JC",
  JD: "JD",
  JE: "JE",
  JF: "JF",
  JG: "JG",
  JH: "JH",
  JI: "JI",
  JJ: "JJ",
  JL: "JL",
  JM: "JM",
  JN: "JN",
  JO: "JO",
  JQ: "JQ",
  JR: "JR",
  JS: "JS",
  JT: "JT",
  JU: "JU",
  JV: "JV",
  JW: "JW",
  JX: "JX",
  JY: "JY",
  K3: "K3",
  K4: "K4",
  K5: "K5",
  K6: "K6",
  K7: "K7",
  K8: "K8",
  K9: "K9",
  KA: "KA",
  KB: "KB",
  KC: "KC",
  KD: "KD",
  KE: "KE",
  KF: "KF",
  KG: "KG",
  KH: "KH",
  KI: "KI",
  KJ: "KJ",
  KK: "KK",
  KL: "KL",
  KM: "KM",
  KN: "KN",
  KO: "KO",
  KP: "KP",
  KQ: "KQ",
  KR: "KR",
  KS: "KS",
  KT: "KT",
  KU: "KU",
  KV: "KV",
  KW: "KW",
  KX: "KX",
  KY: "KY",
  KZ: "KZ",
  L1: "L1",
  L3: "L3",
  L4: "L4",
  L5: "L5",
  L6: "L6",
  L7: "L7",
  L8: "L8",
  L9: "L9",
  LA: "LA",
  LB: "LB",
  LC: "LC",
  LE: "LE",
  LF: "LF",
  LG: "LG",
  LH: "LH",
  LI: "LI",
  LJ: "LJ",
  LK: "LK",
  LL: "LL",
  LM: "LM",
  LN: "LN",
  LO: "LO",
  LP: "LP",
  LQ: "LQ",
  LR: "LR",
  LS: "LS",
  LT: "LT",
  LU: "LU",
  LV: "LV",
  LW: "LW",
  LX: "LX",
  LY: "LY",
  LZ: "LZ",
  M0: "M0",
  M2: "M2",
  M3: "M3",
  M4: "M4",
  M5: "M5",
  M6: "M6",
  M8: "M8",
  M9: "M9",
  MB: "MB",
  MC: "MC",
  MD: "MD",
  ME: "ME",
  MF: "MF",
  MG: "MG",
  MH: "MH",
  MI: "MI",
  MJ: "MJ",
  MK: "MK",
  ML: "ML",
  MM: "MM",
  MN: "MN",
  MO: "MO",
  MP: "MP",
  MQ: "MQ",
  MR: "MR",
  MS: "MS",
  MT: "MT",
  MU: "MU",
  MV: "MV",
  MW: "MW",
  MX: "MX",
  MY: "MY",
  MZ: "MZ",
  N0: "N0",
  N2: "N2",
  N3: "N3",
  N4: "N4",
  N5: "N5",
  N6: "N6",
  N7: "N7",
  N8: "N8",
  N9: "N9",
  NB: "NB",
  NC: "NC",
  ND: "ND",
  NE: "NE",
  NF: "NF",
  NG: "NG",
  NH: "NH",
  NI: "NI",
  NJ: "NJ",
  NK: "NK",
  NL: "NL",
  NM: "NM",
  NN: "NN",
  NO: "NO",
  NP: "NP",
  NQ: "NQ",
  NR: "NR",
  NS: "NS",
  NT: "NT",
  NU: "NU",
  NV: "NV",
  NW: "NW",
  NX: "NX",
  NY: "NY",
  NZ: "NZ",
  O2: "O2",
  O4: "O4",
  O5: "O5",
  O7: "O7",
  O9: "O9",
  OA: "OA",
  OB: "OB",
  OC: "OC",
  OD: "OD",
  OE: "OE",
  OF: "OF",
  OG: "OG",
  OH: "OH",
  OI: "OI",
  OJ: "OJ",
  OK: "OK",
  OL: "OL",
  OM: "OM",
  ON: "ON",
  OO: "OO",
  OP: "OP",
  OQ: "OQ",
  OR: "OR",
  OS: "OS",
  OT: "OT",
  OU: "OU",
  OV: "OV",
  OW: "OW",
  OX: "OX",
  OY: "OY",
  OZ: "OZ",
  P0: "P0",
  P1: "P1",
  P2: "P2",
  P3: "P3",
  P4: "P4",
  P5: "P5",
  P6: "P6",
  P8: "P8",
  P9: "P9",
  PA: "PA",
  PB: "PB",
  PC: "PC",
  PD: "PD",
  PE: "PE",
  PF: "PF",
  PG: "PG",
  PH: "PH",
  PI: "PI",
  PJ: "PJ",
  PK: "PK",
  PL: "PL",
  PM: "PM",
  PN: "PN",
  PO: "PO",
  PP: "PP",
  PQ: "PQ",
  PR: "PR",
  PS: "PS",
  PT: "PT",
  PU: "PU",
  PV: "PV",
  PW: "PW",
  PX: "PX",
  PY: "PY",
  PZ: "PZ",
  Q0: "Q0",
  Q1: "Q1",
  Q2: "Q2",
  Q3: "Q3",
  Q4: "Q4",
  Q5: "Q5",
  Q7: "Q7",
  Q8: "Q8",
  Q9: "Q9",
  QA: "QA",
  QB: "QB",
  QC: "QC",
  QD: "QD",
  QE: "QE",
  QF: "QF",
  QG: "QG",
  QH: "QH",
  QJ: "QJ",
  QK: "QK",
  QL: "QL",
  QM: "QM",
  QN: "QN",
  QO: "QO",
  QP: "QP",
  QQ: "QQ",
  QR: "QR",
  QS: "QS",
  QT: "QT",
  QU: "QU",
  QV: "QV",
  QW: "QW",
  QX: "QX",
  QY: "QY",
  QZ: "QZ",
  R0: "R0",
  R2: "R2",
  R3: "R3",
  R4: "R4",
  R5: "R5",
  R6: "R6",
  R7: "R7",
  R8: "R8",
  R9: "R9",
  RA: "RA",
  RB: "RB",
  RC: "RC",
  RE: "RE",
  RF: "RF",
  RG: "RG",
  RH: "RH",
  RI: "RI",
  RJ: "RJ",
  RK: "RK",
  RL: "RL",
  RM: "RM",
  RN: "RN",
  RO: "RO",
  RP: "RP",
  RQ: "RQ",
  RR: "RR",
  RS: "RS",
  RT: "RT",
  RU: "RU",
  RV: "RV",
  RW: "RW",
  RX: "RX",
  RY: "RY",
  RZ: "RZ",
  S0: "S0",
  S1: "S1",
  S2: "S2",
  S3: "S3",
  S4: "S4",
  S5: "S5",
  S6: "S6",
  S7: "S7",
  S8: "S8",
  S9: "S9",
  SA: "SA",
  SB: "SB",
  SC: "SC",
  SD: "SD",
  SF: "SF",
  SG: "SG",
  SH: "SH",
  SI: "SI",
  SJ: "SJ",
  SK: "SK",
  SL: "SL",
  SM: "SM",
  SN: "SN",
  SO: "SO",
  SP: "SP",
  SQ: "SQ",
  SR: "SR",
  SS: "SS",
  ST: "ST",
  SU: "SU",
  SV: "SV",
  SW: "SW",
  SX: "SX",
  SY: "SY",
  SZ: "SZ",
  T0: "T0",
  T1: "T1",
  T2: "T2",
  T3: "T3",
  T4: "T4",
  T5: "T5",
  T6: "T6",
  T7: "T7",
  T9: "T9",
  TA: "TA",
  TB: "TB",
  TC: "TC",
  TD: "TD",
  TE: "TE",
  TF: "TF",
  TG: "TG",
  TH: "TH",
  TI: "TI",
  TJ: "TJ",
  TK: "TK",
  TL: "TL",
  TM: "TM",
  TN: "TN",
  TO: "TO",
  TP: "TP",
  TQ: "TQ",
  TR: "TR",
  TS: "TS",
  TT: "TT",
  TU: "TU",
  TV: "TV",
  TW: "TW",
  TX: "TX",
  TY: "TY",
  U1: "U1",
  U2: "U2",
  U3: "U3",
  U4: "U4",
  U5: "U5",
  U6: "U6",
  U7: "U7",
  U8: "U8",
  U9: "U9",
  UA: "UA",
  UB: "UB",
  UC: "UC",
  UD: "UD",
  UE: "UE",
  UF: "UF",
  UG: "UG",
  UH: "UH",
  UI: "UI",
  UJ: "UJ",
  UK: "UK",
  UL: "UL",
  UM: "UM",
  UN: "UN",
  UO: "UO",
  UP: "UP",
  UQ: "UQ",
  UR: "UR",
  US: "US",
  UT: "UT",
  UU: "UU",
  UV: "UV",
  UX: "UX",
  UY: "UY",
  UZ: "UZ",
  V0: "V0",
  V1: "V1",
  V2: "V2",
  V3: "V3",
  V4: "V4",
  V5: "V5",
  V6: "V6",
  V7: "V7",
  V8: "V8",
  V9: "V9",
  VA: "VA",
  VB: "VB",
  VC: "VC",
  VD: "VD",
  VE: "VE",
  VF: "VF",
  VG: "VG",
  VH: "VH",
  VI: "VI",
  VJ: "VJ",
  VK: "VK",
  VL: "VL",
  VM: "VM",
  VN: "VN",
  VO: "VO",
  VP: "VP",
  VQ: "VQ",
  VR: "VR",
  VS: "VS",
  VT: "VT",
  VU: "VU",
  VV: "VV",
  VW: "VW",
  VX: "VX",
  VY: "VY",
  VZ: "VZ",
  W1: "W1",
  W2: "W2",
  W3: "W3",
  W4: "W4",
  W5: "W5",
  W6: "W6",
  W7: "W7",
  W8: "W8",
  W9: "W9",
  WA: "WA",
  WB: "WB",
  WC: "WC",
  WD: "WD",
  WE: "WE",
  WF: "WF",
  WG: "WG",
  WH: "WH",
  WI: "WI",
  WJ: "WJ",
  WK: "WK",
  WL: "WL",
  WM: "WM",
  WN: "WN",
  WO: "WO",
  WP: "WP",
  WQ: "WQ",
  WR: "WR",
  WS: "WS",
  WT: "WT",
  WU: "WU",
  WV: "WV",
  WW: "WW",
  WX: "WX",
  WY: "WY",
  WZ: "WZ",
  X1: "X1",
  X3: "X3",
  X4: "X4",
  X6: "X6",
  X7: "X7",
  X9: "X9",
  XB: "XB",
  XC: "XC",
  XD: "XD",
  XE: "XE",
  XF: "XF",
  XG: "XG",
  XH: "XH",
  XJ: "XJ",
  XK: "XK",
  XL: "XL",
  XM: "XM",
  XN: "XN",
  XO: "XO",
  XP: "XP",
  XQ: "XQ",
  XR: "XR",
  XS: "XS",
  XT: "XT",
  XU: "XU",
  XW: "XW",
  XY: "XY",
  XZ: "XZ",
  Y0: "Y0",
  Y1: "Y1",
  Y2: "Y2",
  Y3: "Y3",
  Y4: "Y4",
  Y5: "Y5",
  Y6: "Y6",
  Y7: "Y7",
  Y8: "Y8",
  Y9: "Y9",
  YA: "YA",
  YB: "YB",
  YC: "YC",
  YD: "YD",
  YE: "YE",
  YG: "YG",
  YH: "YH",
  YI: "YI",
  YJ: "YJ",
  YK: "YK",
  YL: "YL",
  YM: "YM",
  YN: "YN",
  YO: "YO",
  YP: "YP",
  YQ: "YQ",
  YR: "YR",
  YS: "YS",
  YT: "YT",
  YU: "YU",
  YV: "YV",
  YW: "YW",
  YX: "YX",
  YZ: "YZ",
  Z0: "Z0",
  Z2: "Z2",
  Z3: "Z3",
  Z4: "Z4",
  Z5: "Z5",
  Z6: "Z6",
  Z7: "Z7",
  Z8: "Z8",
  Z9: "Z9",
  ZA: "ZA",
  ZB: "ZB",
  ZC: "ZC",
  ZD: "ZD",
  ZE: "ZE",
  ZF: "ZF",
  ZG: "ZG",
  ZH: "ZH",
  ZI: "ZI",
  ZJ: "ZJ",
  ZK: "ZK",
  ZL: "ZL",
  ZM: "ZM",
  ZN: "ZN",
  ZP: "ZP",
  ZQ: "ZQ",
  ZR: "ZR",
  ZS: "ZS",
  ZT: "ZT",
  ZU: "ZU",
  ZV: "ZV",
  ZW: "ZW",
  ZX: "ZX",
  ZY: "ZY",
  ZZ: "ZZ",
  _0B: "_0B",
  _0C: "_0C",
  _0J: "_0J",
  _0O: "_0O",
  _0P: "_0P",
  _0V: "_0V",
  _0W: "_0W",
  _1A: "_1A",
  _1B: "_1B",
  _1C: "_1C",
  _1D: "_1D",
  _1E: "_1E",
  _1F: "_1F",
  _1G: "_1G",
  _1H: "_1H",
  _1I: "_1I",
  _1J: "_1J",
  _1K: "_1K",
  _1L: "_1L",
  _1M: "_1M",
  _1N: "_1N",
  _1O: "_1O",
  _1P: "_1P",
  _1Q: "_1Q",
  _1R: "_1R",
  _1S: "_1S",
  _1T: "_1T",
  _1U: "_1U",
  _1V: "_1V",
  _1W: "_1W",
  _1X: "_1X",
  _1Y: "_1Y",
  _1Z: "_1Z",
  _2A: "_2A",
  _2B: "_2B",
  _2C: "_2C",
  _2D: "_2D",
  _2E: "_2E",
  _2F: "_2F",
  _2G: "_2G",
  _2H: "_2H",
  _2I: "_2I",
  _2J: "_2J",
  _2K: "_2K",
  _2L: "_2L",
  _2M: "_2M",
  _2N: "_2N",
  _2O: "_2O",
  _2P: "_2P",
  _2Q: "_2Q",
  _2R: "_2R",
  _2S: "_2S",
  _2T: "_2T",
  _2U: "_2U",
  _2V: "_2V",
  _2W: "_2W",
  _2Z: "_2Z",
  _3A: "_3A",
  _3B: "_3B",
  _3C: "_3C",
  _3D: "_3D",
  _3E: "_3E",
  _3F: "_3F",
  _3G: "_3G",
  _3H: "_3H",
  _3I: "_3I",
  _3J: "_3J",
  _3K: "_3K",
  _3L: "_3L",
  _3M: "_3M",
  _3N: "_3N",
  _3O: "_3O",
  _3P: "_3P",
  _3Q: "_3Q",
  _3R: "_3R",
  _3S: "_3S",
  _3T: "_3T",
  _3U: "_3U",
  _3V: "_3V",
  _3W: "_3W",
  _3X: "_3X",
  _3Z: "_3Z",
  _4A: "_4A",
  _4B: "_4B",
  _4C: "_4C",
  _4D: "_4D",
  _4E: "_4E",
  _4F: "_4F",
  _4G: "_4G",
  _4H: "_4H",
  _4I: "_4I",
  _4J: "_4J",
  _4K: "_4K",
  _4L: "_4L",
  _4M: "_4M",
  _4N: "_4N",
  _4O: "_4O",
  _4P: "_4P",
  _4Q: "_4Q",
  _4R: "_4R",
  _4S: "_4S",
  _4T: "_4T",
  _4U: "_4U",
  _4V: "_4V",
  _4W: "_4W",
  _4X: "_4X",
  _4Y: "_4Y",
  _4Z: "_4Z",
  _5B: "_5B",
  _5C: "_5C",
  _5D: "_5D",
  _5E: "_5E",
  _5F: "_5F",
  _5H: "_5H",
  _5I: "_5I",
  _5J: "_5J",
  _5K: "_5K",
  _5L: "_5L",
  _5M: "_5M",
  _5N: "_5N",
  _5O: "_5O",
  _5P: "_5P",
  _5R: "_5R",
  _5S: "_5S",
  _5T: "_5T",
  _5U: "_5U",
  _5V: "_5V",
  _5W: "_5W",
  _5X: "_5X",
  _5Y: "_5Y",
  _5Z: "_5Z",
  _6A: "_6A",
  _6B: "_6B",
  _6C: "_6C",
  _6D: "_6D",
  _6E: "_6E",
  _6F: "_6F",
  _6G: "_6G",
  _6H: "_6H",
  _6I: "_6I",
  _6J: "_6J",
  _6K: "_6K",
  _6L: "_6L",
  _6M: "_6M",
  _6N: "_6N",
  _6O: "_6O",
  _6Q: "_6Q",
  _6R: "_6R",
  _6S: "_6S",
  _6T: "_6T",
  _6V: "_6V",
  _6W: "_6W",
  _6Y: "_6Y",
  _6Z: "_6Z",
  _7A: "_7A",
  _7B: "_7B",
  _7C: "_7C",
  _7D: "_7D",
  _7E: "_7E",
  _7F: "_7F",
  _7G: "_7G",
  _7H: "_7H",
  _7I: "_7I",
  _7J: "_7J",
  _7K: "_7K",
  _7L: "_7L",
  _7M: "_7M",
  _7N: "_7N",
  _7O: "_7O",
  _7P: "_7P",
  _7Q: "_7Q",
  _7R: "_7R",
  _7S: "_7S",
  _7T: "_7T",
  _7U: "_7U",
  _7V: "_7V",
  _7W: "_7W",
  _7Y: "_7Y",
  _7Z: "_7Z",
  _8A: "_8A",
  _8B: "_8B",
  _8C: "_8C",
  _8D: "_8D",
  _8E: "_8E",
  _8F: "_8F",
  _8G: "_8G",
  _8H: "_8H",
  _8I: "_8I",
  _8J: "_8J",
  _8L: "_8L",
  _8M: "_8M",
  _8N: "_8N",
  _8P: "_8P",
  _8Q: "_8Q",
  _8R: "_8R",
  _8S: "_8S",
  _8T: "_8T",
  _8U: "_8U",
  _8V: "_8V",
  _8W: "_8W",
  _8Y: "_8Y",
  _8Z: "_8Z",
  _9A: "_9A",
  _9B: "_9B",
  _9C: "_9C",
  _9D: "_9D",
  _9E: "_9E",
  _9F: "_9F",
  _9G: "_9G",
  _9H: "_9H",
  _9I: "_9I",
  _9J: "_9J",
  _9K: "_9K",
  _9L: "_9L",
  _9M: "_9M",
  _9N: "_9N",
  _9P: "_9P",
  _9Q: "_9Q",
  _9R: "_9R",
  _9S: "_9S",
  _9T: "_9T",
  _9U: "_9U",
  _9V: "_9V",
  _9W: "_9W",
  _9X: "_9X",
  _9Y: "_9Y",
  ONEWORLD: "ONEWORLD",
  SKYTEAM: "SKYTEAM",
  STAR_ALLIANCE: "STAR_ALLIANCE",
} as const;

export type Airline = (typeof Airline)[keyof typeof Airline];
